### ISSUE TITLE
Add tiproxy component

### ISSUE THREAD

**Issue by wuhuizuo** [PingCAP-QE/artifacts#183]
## Builder
1. Use go 1.21, the builder keep same with `pingcap/tidb`(based centos7.9)
2. Ignore the go toolchain versions in the `go.mod` files.

## Target platforms
- linux/amd64
- linux/arm64
- darwin/amd64
- darwin/arm64

## Requirement

- component package size: 55MiB
- publish TiUP package to TiUP mirror.
- Add it to TiUP offline deploy packages. In `tidb-community-server` and `tidb-enterprise-server`.

**Comment by djshow832** [comment]
> publish TiUP package to TiUP mirror.

I think this step is already done. Refer to https://github.com/PingCAP-QE/ci/pull/2539

**Comment by djshow832** [comment]
LGTM

**Comment by wuhuizuo** [comment]
Update:
1. tiup package also need include the config files same with the [dev Dockerfile]( https://github.com/pingcap/tiproxy/blob/v0.1.2/docker/Dockerfile#L14-L15)
2. keep the builder same with tidb for release product artifacts.
3. Use the `pingcap_base` image as the runtime base image for product container images.

**Comment by xhebox** [comment]
> Update:
> 
>     1. tiup package also need include the config files same with the [dev Dockerfile](https://github.com/pingcap/tiproxy/blob/v0.1.2/docker/Dockerfile?rgh-link-date=2023-12-25T03%3A59%3A55Z#L14-L15)
> 
>     2. keep the builder same with tidb for release product artifacts.
> 
>     3. Use the `pingcap_base` image as the runtime base image for product container images.

1. There is no need to include that, I guess? Even it needs, we need to change the tiup CD pipeline in PingCAP-QE/ci
2. It is using jenkins to build, it is the same builder.
3. That is another thing, I think. Tiup offline package will download tiup tarballs instead of docker images?

**Comment by wuhuizuo** [comment]
> 3\. package

It's container image. I suggest to use the same base runtime image as tidb, tikv, pd, and other components for security governance and monitoring.

@xhebox
